/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <unistd.h>
#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{  
  GtkWidget *menu_liste_electorale;
  GtkWidget *ajout_liste;
  GtkWidget *afficher_liste_electorale;
  GtkWidget *modifier_liste;
	GtkWidget* vote;
  GtkWidget *Espace_Reclamation_1;  
GtkWidget *label;
GtkWidget *label1;
  GtkWidget *mod;
  GtkWidget *af;
  GtkWidget *aj;
  GtkWidget *labelAwrong;
GtkWidget *Login;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
  char ch[100], path[100];
  getcwd(ch, sizeof(ch));
  sprintf(path, "%s/../pixmaps",ch);
  add_pixmap_directory (path);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 /* menu_liste_electorale = create_menu_liste_electorale ();
  gtk_widget_show (menu_liste_electorale);
   Espace_Reclamation_1 = create_Espace_Reclamation_1 ();
  gtk_widget_show (Espace_Reclamation_1);
 label=lookup_widget(Espace_Reclamation_1,"label25");
label1=lookup_widget(Espace_Reclamation_1,"label26");
gtk_widget_hide (label);
gtk_widget_hide (label1);
  /*
ajout_liste = create_ajout_liste ();
  gtk_widget_show (ajout_liste);
  afficher_liste_electorale = create_afficher_liste_electorale ();
  gtk_widget_show (afficher_liste_electorale);
  modifier_liste = create_modifier_liste ();
  gtk_widget_show (modifier_liste);

vote = create_vote();
gtk_widget_show(vote);
*/
Login=create_Login ();
  gtk_widget_show (Login);
  labelAwrong=lookup_widget(Login,"labelAwrong");
  gtk_widget_hide (labelAwrong);
  gtk_main ();
  return 0;
}

